### ISSUE TITLE
Error handling response: TypeError: $(...).modal is not a function

### ISSUE THREAD

**Issue by hungdev** [ovaqlab/simpleDialog#2]
hi @ovaqlab can you help me?
![image](https://user-images.githubusercontent.com/12009276/55698245-2d164200-59ef-11e9-98c6-700f59b7e5dd.png)

**Comment by hungdev** [comment]
so sorry, that my mistake. after add bootstrap.js, it does not show errors anymore. But it does not display modal.

**Comment by ovaqlab** [comment]
@hungdev Did you import bootstrap javascript files? Also, check any error displayed in the console.
